// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateClass(arg1) {
  return window['go']['main']['App']['CreateClass'](arg1);
}

export function CreateClassSubject(arg1) {
  return window['go']['main']['App']['CreateClassSubject'](arg1);
}

export function CreateSubject(arg1) {
  return window['go']['main']['App']['CreateSubject'](arg1);
}

export function DeleteClass(arg1) {
  return window['go']['main']['App']['DeleteClass'](arg1);
}

export function DeleteClassSubject(arg1) {
  return window['go']['main']['App']['DeleteClassSubject'](arg1);
}

export function DeleteSubject(arg1) {
  return window['go']['main']['App']['DeleteSubject'](arg1);
}

export function GetAllClassSubjects() {
  return window['go']['main']['App']['GetAllClassSubjects']();
}

export function GetAllClasses() {
  return window['go']['main']['App']['GetAllClasses']();
}

export function GetAllSubjects() {
  return window['go']['main']['App']['GetAllSubjects']();
}

export function GetClassById(arg1) {
  return window['go']['main']['App']['GetClassById'](arg1);
}

export function GetClassSubjectById(arg1) {
  return window['go']['main']['App']['GetClassSubjectById'](arg1);
}

export function GetSubjectById(arg1) {
  return window['go']['main']['App']['GetSubjectById'](arg1);
}

export function GetTimetableByDayAndHour(arg1, arg2) {
  return window['go']['main']['App']['GetTimetableByDayAndHour'](arg1, arg2);
}

export function UpdateClass(arg1) {
  return window['go']['main']['App']['UpdateClass'](arg1);
}

export function UpdateClassSubject(arg1) {
  return window['go']['main']['App']['UpdateClassSubject'](arg1);
}

export function UpdateSubject(arg1) {
  return window['go']['main']['App']['UpdateSubject'](arg1);
}
