// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {DTOs} from '../models';

export function CreateClass(arg1:DTOs.CreateClassDto):Promise<DTOs.CreateClassResponseDto>;

export function CreateClassSubject(arg1:DTOs.CreateClassSubjectDTO):Promise<DTOs.CreateClassSubjectResponseDTO>;

export function CreateSubject(arg1:DTOs.CreateSubjectDto):Promise<DTOs.CreateSubjectResponseDto>;

export function DeleteClass(arg1:DTOs.DeleteClassDto):Promise<DTOs.DeleteClassResponseDto>;

export function DeleteClassSubject(arg1:DTOs.DeleteClassSubjectDTO):Promise<DTOs.DeleteClassSubjectResponseDTO>;

export function DeleteSubject(arg1:DTOs.DeleteSubjectDto):Promise<DTOs.DeleteSubjectResponseDto>;

export function GetAllClassSubjects():Promise<Array<DTOs.ClassSubjectsDTO>>;

export function GetAllClasses():Promise<Array<DTOs.ClassDto>>;

export function GetAllSubjects():Promise<Array<DTOs.SubjectDto>>;

export function GetClassById(arg1:string):Promise<DTOs.ClassDto>;

export function GetClassSubjectById(arg1:string):Promise<DTOs.ClassSubjectsDTO>;

export function GetSubjectById(arg1:string):Promise<DTOs.SubjectDto>;

export function UpdateClass(arg1:DTOs.UpdateClassDto):Promise<DTOs.UpdateClassResponseDto>;

export function UpdateClassSubject(arg1:DTOs.UpdateClassSubjectDTO):Promise<DTOs.UpdateClassSubjectResponseDTO>;

export function UpdateSubject(arg1:DTOs.UpdateSubjectDto):Promise<DTOs.UpdateSubjectResponseDto>;
